[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js","stripe"]

[[headers]]
for = "/.netlify/functions/payment-success"
  [headers.values]
  Content-Type = "application/json"
