create table if not exists orders (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  address text not null,
  cart jsonb not null,
  total numeric not null,
  payment_status text not null default 'pending',
  stripe_session_id text,
  created_at timestamp with time zone default now()
);